# Generated by Django 3.2.12 on 2023-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_setup_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
